### ISSUE TITLE
The 3D bounding box tracking project sometimes generates invalid JSON files

### ISSUE THREAD

**Issue by qiank10** [ucbdrive/scalabel#343] opened 2019-12-06 10:46 UTC
**Describe the bug**
Sometimes the 3D bounding box tracking project generates invalid JSON files when the save button is clicked. As a result, the bounding boxes cannot be reloaded when reopening the task.

**To Reproduce**
1. Run the server
2. Create a 3D bounding box tracking project
3. Open the task 0
4. Place a car-type box, translate it somewhere in the first frame, then translate it somewhere in the last frame. No scaling or rotating operations are performed.
5. Refresh the task webpage, and the boxes disappear. In the saved JSON file, there are additional 24 ''sensorDataLoaded'' attributes appended at the end of the file.

**Expected behavior**
The JSON file is valid and saves all the boxes labeled.

**Desktop (please complete the following information):**
 - OS: Linux ub-gpux4 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Browser FireFox
 - Version 70.0.1

**Comment by gycn** [comment] 2019-12-06 16:50
Did you press the save button before refreshing?

**Comment by qiank10** [comment] 2019-12-06 16:58
Right. I press the save button before refreshing so that a JSON file is generated in the saved folder.

**Comment by gycn** [comment] 2019-12-06 18:14
Which config file are you using?

**Comment by qiank10** [comment] 2019-12-06 18:31
default_config.yml

**Comment by gycn** [comment] 2019-12-06 18:35
Ok, and are using the docker to run the server with the command in the readme?

**Comment by qiank10** [comment] 2019-12-06 18:43
Yes, except that I mount another folder to /opt/scalabel/data/.

Is it possible that multiple threads write to the same JSON file? Following is the end of a JSON file I get.
`"session":{"id":"","startTime":0,"itemStatuses":[{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}},{"sensorDataLoaded":{"-1":false}}]}}aded":{"-1":false}}]}}`
It is like that a JSON string is covered by a shorted one.

**Comment by gycn** [comment] 2019-12-06 19:12
Could you attach the entire JSON file? The `sensorDataLoaded` fields are correct, but I do see what you mean since the last one is cut off. However, if you are using latest master and the default config, there should be only one thread writing to the file. @ChrisP19 Can you help with this?

**Comment by qiank10** [comment] 2019-12-06 20:09
The link to the JSON file is as follows:
https://drive.google.com/file/d/1tYSQjzNetouXXNwbhYfKcvx1DeuWYY6Z/view?usp=sharing

Besides, I output the saving path in the `save` function in the `file_storage.ts`, it seems that the function is invoked multiple times with one click of the save or submit button.
![image](https://user-images.githubusercontent.com/1515092/70352990-39be9480-1821-11ea-8b76-a64f58cc9311.png)

**Comment by gycn** [comment] 2019-12-06 20:27
@ChrisP19, it seems like the issue is here, line 64 in `hub.ts`: 
![image](https://user-images.githubusercontent.com/7757242/70354042-8a36f180-1823-11ea-989b-9e50c2eb585c.png)
The store in the NodeJS server does an async save whenever an action is received. Since we dispatch all the actions whenever we save, this is likely causing a race condition because save is asynchronous. Is there some way we can make the save synchronous?

**Comment by gycn** [comment] 2019-12-06 20:35
@qiank10 A temporary solution would be to save more frequently. We also have a beta feature called auto-save which can be enabled by setting the `autosave` flag in the config file. In this case, the server will automatically save your project whenever you make a change. Enabling this mechanism should prevent these race conditions

**Comment by gycn** [comment] 2019-12-06 21:46
@qiank10 I believe this issue has been fixed by #345. Could you please check?

**Comment by qiank10** [comment] 2019-12-06 23:55
@gycn @ChrisP19 I have checked the update. The boxes can be correctly saved and reloaded now. Thank you very much!

**Closed** 2019-12-09 19:39 UTC
